server:
  port: 9999

spring:
  application:
    name: eureka


eureka:
  server:
    enable-self-preservation: false #是否启用自动保护机制，默认为true
    eviction-interval-timer-in-ms: 200 #清理间隔(单位毫秒,默认是60*1000ms)
  client:
    register-with-eureka: false #false表示不向注册中心注册自己
    fetch-registry: false # false表示不需要去检索服务
    service-url:
      defaultZone: http://localhost:9999/eureka/
  instance:
    instance-id: ${spring.application.name}
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 15
    lease-renewal-interval-in-seconds: 5
    health-check-url-path: /actuator/health

